name: 'Setup Rails app'
description: 'Setup the environment for running the Rails app'

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Install Node modules
      run: |
        node --version
        yarn install --frozen-lockfile
      shell: bash

    - name: Setup environment variables
      run: cp config/env.example .env
      shell: bash

    - name: Setup test database
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://tps_test@localhost:5432/tps_test"
      run: |
        bin/rails db:create db:schema:load db:migrate
        git diff --exit-code -- db/schema.rb || (echo "Schema.rb has not been updated after migration. Please update it." && false)
      shell: bash
