name: 'Setup Rails assets'
description: 'Pre-compile and cache the app assets'

runs:
  using: composite
  steps:
    - name: Assets cache
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          public/assets
          public/vite-test
          public/vite
          tmp/cache/vite
        key: asset-cache-${{ runner.os }}-${{ hashFiles('package.json', 'patches/**/*.patch', 'app/javascript/**', 'app/assets/**', 'vite.config.ts') }}
        restore-keys: |
          asset-cache-${{ runner.os }}-${{ hashFiles('package.json', 'patches/**/*.patch', 'app/javascript/**', 'app/assets/**') }}
          asset-cache-${{ runner.os }}-${{ hashFiles('package.json', 'patches/**/*.patch') }}
          asset-cache-${{ runner.os }}-

    - name: Setup bun and node modules
      uses: ./.github/actions/ci-setup-bun-node
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Precompile assets
      env:
        RAILS_ENV: test
      run: bin/rails assets:precompile --trace
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
